package co.edu.sena.gymtrack.domain;

import static co.edu.sena.gymtrack.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class GymServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGymServiceAllPropertiesEquals(GymService expected, GymService actual) {
        assertGymServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertGymServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGymServiceAllUpdatablePropertiesEquals(GymService expected, GymService actual) {
        assertGymServiceUpdatableFieldsEquals(expected, actual);
        assertGymServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGymServiceAutoGeneratedPropertiesEquals(GymService expected, GymService actual) {
        assertThat(actual)
            .as("Verify GymService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGymServiceUpdatableFieldsEquals(GymService expected, GymService actual) {
        assertThat(actual)
            .as("Verify GymService relevant properties")
            .satisfies(a -> assertThat(a.getServiceName()).as("check serviceName").isEqualTo(expected.getServiceName()))
            .satisfies(a -> assertThat(a.getServiceDescription()).as("check serviceDescription").isEqualTo(expected.getServiceDescription())
            )
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGymServiceUpdatableRelationshipsEquals(GymService expected, GymService actual) {
        assertThat(actual)
            .as("Verify GymService relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
