package co.edu.sena.gymtrack.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IncidentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidentAllPropertiesEquals(Incident expected, Incident actual) {
        assertIncidentAutoGeneratedPropertiesEquals(expected, actual);
        assertIncidentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidentAllUpdatablePropertiesEquals(Incident expected, Incident actual) {
        assertIncidentUpdatableFieldsEquals(expected, actual);
        assertIncidentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidentAutoGeneratedPropertiesEquals(Incident expected, Incident actual) {
        assertThat(actual)
            .as("Verify Incident auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidentUpdatableFieldsEquals(Incident expected, Incident actual) {
        assertThat(actual)
            .as("Verify Incident relevant properties")
            .satisfies(a -> assertThat(a.getIncidentType()).as("check incidentType").isEqualTo(expected.getIncidentType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getReportedDate()).as("check reportedDate").isEqualTo(expected.getReportedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidentUpdatableRelationshipsEquals(Incident expected, Incident actual) {
        // empty method
    }
}
