package co.edu.sena.gymtrack.domain;

import static co.edu.sena.gymtrack.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InvoiceServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceServiceAllPropertiesEquals(InvoiceService expected, InvoiceService actual) {
        assertInvoiceServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertInvoiceServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceServiceAllUpdatablePropertiesEquals(InvoiceService expected, InvoiceService actual) {
        assertInvoiceServiceUpdatableFieldsEquals(expected, actual);
        assertInvoiceServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceServiceAutoGeneratedPropertiesEquals(InvoiceService expected, InvoiceService actual) {
        assertThat(actual)
            .as("Verify InvoiceService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceServiceUpdatableFieldsEquals(InvoiceService expected, InvoiceService actual) {
        assertThat(actual)
            .as("Verify InvoiceService relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            )
            .satisfies(a ->
                assertThat(a.getSalePrice()).as("check salePrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSalePrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceServiceUpdatableRelationshipsEquals(InvoiceService expected, InvoiceService actual) {
        assertThat(actual)
            .as("Verify InvoiceService relationships")
            .satisfies(a -> assertThat(a.getInvoice()).as("check invoice").isEqualTo(expected.getInvoice()))
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
