package co.edu.sena.gymtrack.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MachineIncidentsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineIncidentsAllPropertiesEquals(MachineIncidents expected, MachineIncidents actual) {
        assertMachineIncidentsAutoGeneratedPropertiesEquals(expected, actual);
        assertMachineIncidentsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineIncidentsAllUpdatablePropertiesEquals(MachineIncidents expected, MachineIncidents actual) {
        assertMachineIncidentsUpdatableFieldsEquals(expected, actual);
        assertMachineIncidentsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineIncidentsAutoGeneratedPropertiesEquals(MachineIncidents expected, MachineIncidents actual) {
        assertThat(actual)
            .as("Verify MachineIncidents auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineIncidentsUpdatableFieldsEquals(MachineIncidents expected, MachineIncidents actual) {
        assertThat(actual)
            .as("Verify MachineIncidents relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getImage()).as("check image").isEqualTo(expected.getImage()))
            .satisfies(a -> assertThat(a.getImageContentType()).as("check image contenty type").isEqualTo(expected.getImageContentType()))
            .satisfies(a -> assertThat(a.getVideo()).as("check video").isEqualTo(expected.getVideo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineIncidentsUpdatableRelationshipsEquals(MachineIncidents expected, MachineIncidents actual) {
        assertThat(actual)
            .as("Verify MachineIncidents relationships")
            .satisfies(a -> assertThat(a.getIncident()).as("check incident").isEqualTo(expected.getIncident()))
            .satisfies(a -> assertThat(a.getMachine()).as("check machine").isEqualTo(expected.getMachine()));
    }
}
