package co.edu.sena.gymtrack.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MachineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineAllPropertiesEquals(Machine expected, Machine actual) {
        assertMachineAutoGeneratedPropertiesEquals(expected, actual);
        assertMachineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineAllUpdatablePropertiesEquals(Machine expected, Machine actual) {
        assertMachineUpdatableFieldsEquals(expected, actual);
        assertMachineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineAutoGeneratedPropertiesEquals(Machine expected, Machine actual) {
        assertThat(actual)
            .as("Verify Machine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineUpdatableFieldsEquals(Machine expected, Machine actual) {
        assertThat(actual)
            .as("Verify Machine relevant properties")
            .satisfies(a -> assertThat(a.getSerial()).as("check serial").isEqualTo(expected.getSerial()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineUpdatableRelationshipsEquals(Machine expected, Machine actual) {
        assertThat(actual)
            .as("Verify Machine relationships")
            .satisfies(a -> assertThat(a.getAdmin()).as("check admin").isEqualTo(expected.getAdmin()));
    }
}
