package co.edu.sena.gymtrack.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserDataAsserts {

    public static void assertUserDataAllPropertiesEquals(UserData expected, UserData actual) {
        assertUserDataAutoGeneratedPropertiesEquals(expected, actual);
        assertUserDataAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertUserDataAllUpdatablePropertiesEquals(UserData expected, UserData actual) {
        assertUserDataUpdatableFieldsEquals(expected, actual);
        assertUserDataUpdatableRelationshipsEquals(expected, actual);
    }

    public static void assertUserDataAutoGeneratedPropertiesEquals(UserData expected, UserData actual) {
        assertThat(actual)
            .as("Verify UserData auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    public static void assertUserDataUpdatableFieldsEquals(UserData expected, UserData actual) {
        assertThat(actual)
            .as("Verify UserData relevant properties")
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getSecondName()).as("check secondName").isEqualTo(expected.getSecondName()))
            .satisfies(a -> assertThat(a.getFirstLastName()).as("check firstLastName").isEqualTo(expected.getFirstLastName()))
            .satisfies(a -> assertThat(a.getSecondLastName()).as("check secondLastName").isEqualTo(expected.getSecondLastName()))
            .satisfies(a -> assertThat(a.getDocumentNumber()).as("check documentNumber").isEqualTo(expected.getDocumentNumber()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getBirthDate()).as("check birthDate").isEqualTo(expected.getBirthDate()));
    }

    public static void assertUserDataUpdatableRelationshipsEquals(UserData expected, UserData actual) {
        assertThat(actual)
            .as("Verify UserData relationships")
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()));
    }
}
