package co.edu.sena.gymtrack.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserDataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDataAllPropertiesEquals(UserData expected, UserData actual) {
        assertUserDataAutoGeneratedPropertiesEquals(expected, actual);
        assertUserDataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDataAllUpdatablePropertiesEquals(UserData expected, UserData actual) {
        assertUserDataUpdatableFieldsEquals(expected, actual);
        assertUserDataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDataAutoGeneratedPropertiesEquals(UserData expected, UserData actual) {
        assertThat(actual)
            .as("Verify UserData auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDataUpdatableFieldsEquals(UserData expected, UserData actual) {
        assertThat(actual)
            .as("Verify UserData relevant properties")
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getSecondName()).as("check secondName").isEqualTo(expected.getSecondName()))
            .satisfies(a -> assertThat(a.getFirstLastName()).as("check firstLastName").isEqualTo(expected.getFirstLastName()))
            .satisfies(a -> assertThat(a.getSecondLastName()).as("check secondLastName").isEqualTo(expected.getSecondLastName()))
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()))
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a -> assertThat(a.getBirthDate()).as("check birthDate").isEqualTo(expected.getBirthDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDataUpdatableRelationshipsEquals(UserData expected, UserData actual) {
        assertThat(actual)
            .as("Verify UserData relationships")
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()));
    }
}
